# user need to provide training data dirs & output dirs
data_dir: '/data/ILSVRC2012/ILSVRC/Data/CLS-LOC'
output_dir: 'output'

# basic parameters
epochs: 90
batch_size: 64
pretrained: ''
seed: 0
resume: ''
eval: False
pin_mem: True
log_interval: 50
recovery_interval: 0

# Distributed training parameters
dist_bn: reduce
no_amp: False
use_apex_amp: True

# EasyRobust training parameters
training_mode: advtrain
standard_dataaug_for_advtrain: True

# Data parameters
num_classes: 1000
data_encode_type: byte
crop_pct: 0.875
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

# Model parameters
model: resnet50
input_size: 224
drop: 0.0
drop_path: 0.0
model_ema: False
model_ema_decay: 0.9998
model_ema_force_cpu: False

# Optimizer parameters
opt: sgd
opt_eps: 1.0e-8
opt_betas: null
clip_grad: null
clip_mode: norm
momentum: 0.9
weight_decay: 0.0001

# Learning rate schedule parameters
sched: step
lr: 0.1
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
warmup_lr: 0.0001
min_lr: 1.0e-5
decay_epochs: 30
warmup_epochs: 0
cooldown_epochs: 0
patience_epochs: 0
decay_rate: 0.1

# Augmentation parameters
color_jitter: 0.1
aa: null
smoothing: 0.1
train_interpolation: bicubic
reprob: 0.0
remode: pixel
recount: 0
resplit: False
mixup: 0.0
cutmix: 0.0
cutmix_minmax: null
mixup_prob: 0.0
mixup_switch_prob: 0.0
mixup_mode: batch