# user need to provide training data dirs & output dirs
data_dir: '/data/ILSVRC2012/ILSVRC/Data/CLS-LOC'
output_dir: 'output'

# basic parameters
epochs: 300
batch_size: 32
pretrained: ''
seed: 0
resume: ''
eval: False
pin_mem: True
log_interval: 50
recovery_interval: 0

# Distributed training parameters
dist_bn: reduce
no_amp: False
use_apex_amp: True

# EasyRobust training parameters
training_mode: regular

# Data parameters
num_classes: 1000
data_encode_type: byte
crop_pct: 0.875
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

# Model parameters
model: deit_small_patch16_224
input_size: 224
drop: 0.0
drop_path: 0.1
model_ema: False
model_ema_decay: 0.9998
model_ema_force_cpu: False

# Optimizer parameters
opt: adamw
opt_eps: 1.0e-8
opt_betas: null
clip_grad: null
clip_mode: norm
momentum: 0.9
weight_decay: 0.05

# Learning rate schedule parameters
sched: cosine
lr: 0.001
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
warmup_lr: 1.0e-6
min_lr: 1.0e-5
decay_epochs: 30
warmup_epochs: 5
cooldown_epochs: 10
patience_epochs: 10
decay_rate: 0.1

# Augmentation parameters
color_jitter: 0.4
aa: rand-m9-mstd0.5-inc1
smoothing: 0.1
train_interpolation: bicubic
reprob: 0.25
remode: pixel
recount: 1
resplit: False
mixup: 0.8
cutmix: 1.0
cutmix_minmax: null
mixup_prob: 1.0
mixup_switch_prob: 0.5
mixup_mode: batch